"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { PreviewNotice, PreviewSelect } from "@/components/admin/preview-controls"
import { sampleAttendees, sampleEvent } from "./sample-events"

export type StaffView = "Staff list" | "Editor" | "Attendees" | "Registration" | "Check-in"
export function StaffEvents({ view, onNavigate, checkedIn }: { view: Exclude<StaffView, "Registration" | "Check-in">; onNavigate: (view: StaffView) => void; checkedIn: ReadonlySet<string> }) {
  const [query, setQuery] = useState("")
  const [status, setStatus] = useState("all")
  const [title, setTitle] = useState(sampleEvent.title)
  const [description, setDescription] = useState(sampleEvent.description)
  const [drafted, setDrafted] = useState(false)
  if (view === "Editor") return <form className="flex flex-col gap-5" onSubmit={(event) => { event.preventDefault(); setDrafted(true) }}><h2 className="font-serif text-2xl">Event draft</h2><FieldGroup><Field><FieldLabel htmlFor="event-title">Event title</FieldLabel><Input id="event-title" value={title} required maxLength={150} onChange={(event) => { setTitle(event.target.value); setDrafted(false) }} /></Field><Field><FieldLabel htmlFor="event-description">Description</FieldLabel><Textarea id="event-description" value={description} required maxLength={3000} onChange={(event) => { setDescription(event.target.value); setDrafted(false) }} /></Field></FieldGroup><p className="text-sm text-muted-foreground">{sampleEvent.date} · {sampleEvent.location}. Schedule and capacity are illustrative, not editable operational settings.</p><div className="flex flex-wrap gap-3"><Button type="submit">Preview draft</Button><Button type="button" variant="outline" disabled>Publish unavailable</Button></div>{drafted && <PreviewNotice title="Local draft preview"><strong>{title}</strong><p className="whitespace-pre-wrap break-words">{description}</p><p>Nothing saved or published. Leaving this view discards edits.</p></PreviewNotice>}</form>
  if (view === "Staff list") return <section className="flex flex-col gap-5"><h2 className="font-serif text-2xl">Foundation events</h2><div className="overflow-x-auto rounded-lg border border-border"><Table><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell><p className="font-medium">{sampleEvent.title}</p><p className="text-sm text-muted-foreground">{sampleEvent.date}</p></TableCell><TableCell>Sample draft</TableCell><TableCell><Button variant="outline" onClick={() => onNavigate("Editor")}>Review draft</Button></TableCell></TableRow></TableBody></Table></div><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={() => onNavigate("Attendees")}>View sample attendees</Button><Button variant="outline" onClick={() => onNavigate("Check-in")}>Open check-in preview</Button></div></section>
  const attendees = sampleAttendees.filter((item) => item.eventId === sampleEvent.id).filter((item) => `${item.name} ${item.email}`.toLowerCase().includes(query.toLowerCase()) && (status === "all" || (status === "checked in" ? checkedIn.has(item.reference) : !checkedIn.has(item.reference))))
  return <section className="flex min-w-0 flex-col gap-5"><h2 className="font-serif text-2xl">Sample attendees</h2><FieldGroup><Field><FieldLabel htmlFor="attendee-search">Search sample attendees</FieldLabel><Input id="attendee-search" value={query} onChange={(event) => setQuery(event.target.value)} /></Field><PreviewSelect label="Attendance" value={status} values={["all", "checked in", "not checked in"]} onChange={setStatus} /></FieldGroup><p role="status" className="text-sm text-muted-foreground">{attendees.length} sample result{attendees.length === 1 ? "" : "s"}</p>{attendees.length ? <div className="max-w-full overflow-x-auto rounded-lg border border-border"><Table><TableHeader><TableRow><TableHead>Guest</TableHead><TableHead>Email</TableHead><TableHead>Registration</TableHead><TableHead>Attendance</TableHead></TableRow></TableHeader><TableBody>{attendees.map((item) => <TableRow key={item.reference}><TableCell>{item.name}</TableCell><TableCell>{item.email}</TableCell><TableCell>{item.status}</TableCell><TableCell>{checkedIn.has(item.reference) ? "Checked in (sample)" : "Not checked in"}</TableCell></TableRow>)}</TableBody></Table></div> : <PreviewNotice title="No matching attendees">Try another search or reset the filters.</PreviewNotice>}<div className="flex flex-wrap gap-3"><Button variant="outline" onClick={() => { setQuery(""); setStatus("all") }}>Reset filters</Button><Button onClick={() => onNavigate("Registration")}>Preview registration</Button></div></section>
}
